// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v6.33.0
// source: seckill.proto

package seckillproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuyState int32

const (
	BuyState_SUCCESS BuyState = 0
	BuyState_FAILED  BuyState = 1
	BuyState_WAIT    BuyState = 2
)

// Enum value maps for BuyState.
var (
	BuyState_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILED",
		2: "WAIT",
	}
	BuyState_value = map[string]int32{
		"SUCCESS": 0,
		"FAILED":  1,
		"WAIT":    2,
	}
)

func (x BuyState) Enum() *BuyState {
	p := new(BuyState)
	*p = x
	return p
}

func (x BuyState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuyState) Descriptor() protoreflect.EnumDescriptor {
	return file_seckill_proto_enumTypes[0].Descriptor()
}

func (BuyState) Type() protoreflect.EnumType {
	return &file_seckill_proto_enumTypes[0]
}

func (x BuyState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuyState.Descriptor instead.
func (BuyState) EnumDescriptor() ([]byte, []int) {
	return file_seckill_proto_rawDescGZIP(), []int{0}
}

type SeckillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=productId,proto3" json:"productId,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeckillRequest) Reset() {
	*x = SeckillRequest{}
	mi := &file_seckill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeckillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeckillRequest) ProtoMessage() {}

func (x *SeckillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeckillRequest.ProtoReflect.Descriptor instead.
func (*SeckillRequest) Descriptor() ([]byte, []int) {
	return file_seckill_proto_rawDescGZIP(), []int{0}
}

func (x *SeckillRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SeckillRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *SeckillRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type SeckillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuyState      BuyState               `protobuf:"varint,1,opt,name=buyState,proto3,enum=BuyState" json:"buyState,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeckillResponse) Reset() {
	*x = SeckillResponse{}
	mi := &file_seckill_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeckillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeckillResponse) ProtoMessage() {}

func (x *SeckillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeckillResponse.ProtoReflect.Descriptor instead.
func (*SeckillResponse) Descriptor() ([]byte, []int) {
	return file_seckill_proto_rawDescGZIP(), []int{1}
}

func (x *SeckillResponse) GetBuyState() BuyState {
	if x != nil {
		return x.BuyState
	}
	return BuyState_SUCCESS
}

func (x *SeckillResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_seckill_proto protoreflect.FileDescriptor

var file_seckill_proto_rawDesc = string([]byte{
	0x0a, 0x0d, 0x73, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x5c, 0x0a, 0x0e, 0x53, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x4a, 0x0a,
	0x0f, 0x53, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x25, 0x0a, 0x08, 0x62, 0x75, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x09, 0x2e, 0x42, 0x75, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x08, 0x62,
	0x75, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x2a, 0x2d, 0x0a, 0x08, 0x42, 0x75, 0x79,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53,
	0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x12, 0x08,
	0x0a, 0x04, 0x57, 0x41, 0x49, 0x54, 0x10, 0x02, 0x32, 0x40, 0x0a, 0x0e, 0x53, 0x65, 0x63, 0x6b,
	0x69, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x07, 0x53, 0x65,
	0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x12, 0x0f, 0x2e, 0x53, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x53, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2e,
	0x2f, 0x73, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_seckill_proto_rawDescOnce sync.Once
	file_seckill_proto_rawDescData []byte
)

func file_seckill_proto_rawDescGZIP() []byte {
	file_seckill_proto_rawDescOnce.Do(func() {
		file_seckill_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_seckill_proto_rawDesc), len(file_seckill_proto_rawDesc)))
	})
	return file_seckill_proto_rawDescData
}

var file_seckill_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_seckill_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_seckill_proto_goTypes = []any{
	(BuyState)(0),           // 0: BuyState
	(*SeckillRequest)(nil),  // 1: SeckillRequest
	(*SeckillResponse)(nil), // 2: SeckillResponse
}
var file_seckill_proto_depIdxs = []int32{
	0, // 0: SeckillResponse.buyState:type_name -> BuyState
	1, // 1: SeckillService.Seckill:input_type -> SeckillRequest
	2, // 2: SeckillService.Seckill:output_type -> SeckillResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_seckill_proto_init() }
func file_seckill_proto_init() {
	if File_seckill_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_seckill_proto_rawDesc), len(file_seckill_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_seckill_proto_goTypes,
		DependencyIndexes: file_seckill_proto_depIdxs,
		EnumInfos:         file_seckill_proto_enumTypes,
		MessageInfos:      file_seckill_proto_msgTypes,
	}.Build()
	File_seckill_proto = out.File
	file_seckill_proto_goTypes = nil
	file_seckill_proto_depIdxs = nil
}
