apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: seckill
data:
  SERVICE_IP: "user-service"
  REDIS_ADDR: "host.docker.internal:6380"
  ETCD_ENDPOINTS: "host.docker.internal:2379"
  KAFKA_BROKERS: "host.docker.internal:29092"
  DB_DSN: "root:password@tcp(host.docker.internal:3307)/seckill?charset=utf8mb4&parseTime=True&loc=Local"
---
apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: seckill
type: Opaque
stringData:
  JWT_TOKEN_KEY: "seckill_jwt_secret_key"