apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: seckill
  labels:
    service: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      service: user-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        service: user-service
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: user-service
          image: peter123ouob/user-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
              name: http
            - containerPort: 50050
              name: grpc
          envFrom:
            - configMapRef:
                name: user-service-config
            - secretRef:
                name: user-service-secret
          resources:
            requests:
              cpu: "512m"
              memory: "256Mi"
            limits:
              cpu: "1024m"
              memory: "2Gi"
          startupProbe:
            tcpSocket:
              port: 8083
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: 8083
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8083
            initialDelaySeconds: 5
            periodSeconds: 5

